set(_CATKIN_CURRENT_PACKAGE "coco_ros_launcher")
set(coco_ros_launcher_MAINTAINER "pippo <pippo@todo.todo>")
set(coco_ros_launcher_DEPRECATED "")
set(coco_ros_launcher_VERSION "0.1.0")
set(coco_ros_launcher_BUILD_DEPENDS "roscpp" "std_msgs")
set(coco_ros_launcher_RUN_DEPENDS "roscpp" "std_msgs")
set(coco_ros_launcher_BUILDTOOL_DEPENDS "catkin")