comode: coco::ConnectionBase Class Reference
coco::ConnectionBase Class Reference
#include <ezoro.hpp>
Public Member Functions
ConnectionBase (PortBase *in, PortBase *out, ConnectionPolicy policy)
Constructor.
bool hasNewData () const
Protected Member Functions
void trigger ()
Protected Attributes
FlowStatus data_status_
status of the data in the container
ConnectionPolicy policy_
policy for data management
PortBase * input_ = 0
input port untyped
PortBase * output_ = 0
output port untyped
Detailed Description
Base class for connections
Member Function Documentation
bool coco::ConnectionBase::hasNewData () const inline
Returns
NEW_DATA if new data is present in the Input port
References data_status_.
void coco::ConnectionBase::trigger () protected
Trigger the port to communicate new data is present
References input_, and coco::PortBase::triggerComponent().
Referenced by coco::ConnectionDataL< T >::addData(), coco::ConnectionDataU< T >::addData(), coco::ConnectionBufferU< T >::addData(), and coco::ConnectionBufferL< T >::addData().
The documentation for this class was generated from the following files:
src/ezoro.hpp
src/ezoro.cpp